#!/bin/bash

set -x

set -eo pipefail

# Work out what version of Python we are being used with by looking in
# the /opt/app-root/packages directory.

PYTHON_RUNTIME=${PYTHON_RUNTIME:-`basename /opt/app-root/packages/python-*`}

. /opt/app-root/packages/$PYTHON_RUNTIME/activate

# Populate the wheelhouse directory with compiled Python packages.

PIP_WHEEL_DIR=/opt/app-root/wheelhouse/$PYTHON_RUNTIME
export PIP_WHEEL_DIR

mkdir -p $PIP_WHEEL_DIR

xy=`echo $PYTHON_RUNTIME | sed -e 's/python-\(.*\)$/\1/'`

echo " -----> Generating wheels for Python packages."

pip$xy install "notebook==5.2.*" "jupyterhub==0.8.*"

#pip$xy wheel -r jupyter-notebook.txt
pip$xy wheel -r python-datascience-handbook.txt
