#!/bin/bash

PATH=/opt/app-root/packages/parts/python-3.6/bin:$PATH
export PATH

LD_RUN_PATH=/opt/app-root/packages/parts/python-3.6/lib:$LD_RUN_PATH
export LD_RUN_PATH

LD_LIBRARY_PATH=/opt/app-root/packages/parts/python-3.6/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
