#!/bin/bash

set -x

set -eo pipefail

mkdir -p /opt/app-root/packages/parts

mv /opt/app-root/src/.s2i/packages/parts/python-3.6 /opt/app-root/packages/parts

echo >> /opt/app-root/etc/scl_enable << EOF
. /opt/app-root/packages/parts/python-3.6/activate
EOF
