#!/bin/bash

set -x

set -eo pipefail

# Copy files to src directory for building.

cp -Rf /tmp/src/. /opt/app-root/src/

rm -rf /tmp/src

# Run buildout.

BUILDOUT_CONFIG_FILE=${BUILDOUT_CONFIG_FILE:-buildout.cfg}

buildout -c $BUILDOUT_CONFIG_FILE

# Fixup permissions.

fix-permissions /opt/app-root
